"""
Authoritative Knowledge Base Corpus for Maharashtra Single Window Clearances
Grounded in official policy circulars, acts, and statutory rules.
Authoritative Knowledge Base Corpus for Maharashtra Single Window Clearances (Udyog Samyog)
Grounded in official policy circulars, acts, and statutory rules of Maharashtra Government.
"""
from typing import List, Dict, Any

KB_CHUNKS: List[Dict[str, Any]] = [
    # ── 1. MPCB (Maharashtra Pollution Control Board) ───────────────────────────
    {
        "id": "kb-mpcb-001",
        "doc_id": "mpcb-guidelines-2020",
        "title": "Maharashtra Pollution Control Board - Categorization & Consent Guidelines",
        "issuer": "Maharashtra Pollution Control Board (MPCB)",
        "section": "Clause 2.1: Consent to Establish (CTE) Requirements",
        "text": "Every industrial unit planning to establish a manufacturing or processing facility in Maharashtra must obtain a prior Consent to Establish (CTE) from MPCB under Section 25 of the Water Act 1974 and Section 21 of the Air Act 1981. Red category units require in-depth scrutiny and an Effluent Treatment Plant (ETP) with Zero Liquid Discharge or standard discharge compliance.",
        "text": "Every industrial unit planning to establish a manufacturing or processing facility in Maharashtra must obtain prior Consent to Establish (CTE) from MPCB under Section 25 of the Water (Prevention and Control of Pollution) Act 1974 and Section 21 of the Air (Prevention and Control of Pollution) Act 1981 before starting any site construction. Red category units require in-depth scrutiny, public hearing (where applicable), and an Effluent Treatment Plant (ETP) designed for Zero Liquid Discharge (ZLD) or prescribed inland surface water standards.",
        "lang": "en",
        "tags": ["mpcb", "environmental", "red", "orange", "green", "cte", "effluent"],
        "tags": ["mpcb", "environmental", "cte", "water-act", "air-act", "effluent", "clearance", "परवानगी", "प्रदूषण", "संमती"],
    },
    {
        "id": "kb-mpcb-002",
        "doc_id": "hazard-waste-rules-2016",
        "title": "Hazardous & Other Wastes (Management & Transboundary Movement) Rules",
        "issuer": "Ministry of Environment, Forest and Climate Change / MPCB",
        "section": "Rule 6: Grant of Authorization for Handling Hazardous Waste",
        "text": "Any facility generating, handling, storing, or disposing hazardous chemical waste must obtain specific authorization from MPCB and execute an agreement with a registered Common Hazardous Waste Treatment, Storage and Disposal Facility (CHWTSDF) in Maharashtra.",
        "text": "Any industrial facility generating, handling, storing, or disposing hazardous chemical waste must obtain specific authorization from MPCB using Form 1 and execute a legally binding membership agreement with a registered Common Hazardous Waste Treatment, Storage and Disposal Facility (CHWTSDF) in Maharashtra (such as MEPL Taloja, Ranjangaon, or Butibori) with standard Form 10 manifest tracking.",
        "lang": "en",
        "tags": ["mpcb", "hazardous", "chemical", "waste", "authorization"],
        "tags": ["mpcb", "hazardous", "chemical", "waste", "authorization", "chwtsdf", "कचरा", "धोकादायक"],
    },
    {
        "id": "kb-mpcb-003",
        "doc_id": "mpcb-categorization-cpcb-2016",
        "title": "MPCB Industrial Categorization & Pollution Index Criteria",
        "issuer": "Maharashtra Pollution Control Board (MPCB)",
        "section": "Schedule A: Red, Orange, Green, and White Category Classification",
        "text": "Industries in Maharashtra are categorized by Pollution Index (PI) score: Red category (PI score 60 and above, representing high pollution potential including chemicals, dyes, refineries, and heavy metallurgy), Orange category (PI score 41 to 59, moderate pollution like food processing, light engineering, formulation), Green category (PI score 21 to 40, low pollution), and White category (PI score up to 20, non-polluting). White category industries are fully exempted from MPCB Consent to Establish and Consent to Operate; they only require an online self-declaration intimation on the portal.",
        "lang": "en",
        "tags": ["mpcb", "categorization", "red", "orange", "green", "white", "pollution-index", "वर्गवारी", "लाल", "केशरी", "हिरवा", "पांढरा"],
    },
    {
        "id": "kb-mpcb-004",
        "doc_id": "mpcb-cto-renewal-policy",
        "title": "MPCB Consent to Operate (CTO) & Validity Timelines",
        "issuer": "Maharashtra Pollution Control Board (MPCB)",
        "section": "Regulation 5: Commissioning & Consent to Operate Renewal",
        "text": "Before commencing commercial production or trial run, industrial units must obtain Consent to Operate (CTO) from MPCB. CTE remains valid for up to 5 years or until commissioning, whichever is earlier. CTO is granted for 5 years for Red category, 10 years for Orange category, and 15 years for Green category with simplified auto-renewal provision upon submitting compliance certification and requisite statutory fees.",
        "lang": "en",
        "tags": ["mpcb", "cto", "consent-to-operate", "validity", "renewal", "commissioning", "मुदत", "नूतनीकरण"],
    },
    {
        "id": "kb-mpcb-005",
        "doc_id": "mpcb-fee-structure-2023",
        "title": "MPCB Statutory Consent Fee Schedule based on Capital Investment",
        "issuer": "Maharashtra Pollution Control Board (MPCB)",
        "section": "Fee Schedule Notification: Fixed Capital Investment Tiers",
        "text": "MPCB Consent fees are calculated on the gross Capital Investment (Gross Fixed Assets including Land, Building, Plant and Machinery without depreciation). Fee slabs start from ₹5,000 for investments under ₹25 Lakhs, ₹15,000 to ₹50,000 for investments up to ₹5 Crores, ₹75,000 to ₹1,50,000 for ₹5 to ₹25 Crores, scaling up to ₹5 Lakhs or more for Large Mega projects with investments exceeding ₹100 Crores. Fees must be deposited online through the integrated payment gateway.",
        "lang": "en",
        "tags": ["mpcb", "fee", "consent-fee", "capital-investment", "cost", "शुल्क", "फीस", "खर्च"],
    },
    {
        "id": "kb-mpcb-006",
        "doc_id": "mpcb-etp-discharge-standards",
        "title": "MPCB Industrial Effluent & Sewage Treatment Standards",
        "issuer": "Maharashtra Pollution Control Board (MPCB)",
        "section": "Environmental Standards: ETP and STP Discharge Norms",
        "text": "Treated industrial effluent discharged into inland surface water must meet prescribed limits: Biochemical Oxygen Demand (BOD) not exceeding 30 mg/l, Chemical Oxygen Demand (COD) not exceeding 250 mg/l, Total Suspended Solids (TSS) under 100 mg/l, and pH between 5.5 and 9.0. Units in critically polluted areas or outside CETP zones must implement Zero Liquid Discharge (ZLD) with Multi-Effect Evaporators (MEE) and RO systems. Units generating domestic sewage exceeding 10 KLD must install a dedicated Sewage Treatment Plant (STP).",
        "lang": "en",
        "tags": ["mpcb", "etp", "stp", "effluent", "discharge", "bod", "cod", "zld", "मलनिस्सारण", "शुद्धीकरण"],
    },
    {
        "id": "kb-mpcb-007",
        "doc_id": "mpcb-air-stack-emission-norms",
        "title": "Air Pollution Control & Industrial Chimney Stack Height Formula",
        "issuer": "Maharashtra Pollution Control Board (MPCB)",
        "section": "Air Act Regulations: Minimum Stack Height and Scrubber Norms",
        "text": "All industrial chimneys and boiler stacks must comply with the Central Pollution Control Board stack height formula: H = 14 * (Q)^0.3 for fuel burning with sulphur dioxide emissions (where Q is SO2 emission rate in kg/hr), or H = 74 * (Q)^0.27 for particulate matter. In all cases, the minimum stack height for steam boilers is 30 meters from ground level or 3 meters above the highest point of the factory roof, whichever is higher, fitted with sampling port holes and ladder access.",
        "lang": "en",
        "tags": ["mpcb", "air-pollution", "stack", "chimney", "emission", "boiler", "चिमणी", "हवा-प्रदूषण"],
    },

    # ── 2. MIDC (Maharashtra Industrial Development Corporation) ───────────────
    {
        "id": "kb-midc-001",
        "doc_id": "midc-dcr-2020",
        "title": "MIDC Development Control Regulations & Land Allotment Policy",
        "title": "MIDC Development Control Regulations & Building Plan Approvals",
        "issuer": "Maharashtra Industrial Development Corporation (MIDC)",
        "section": "Regulation 4: Building Plan Approval and Setback Norms",
        "text": "All industrial structures within MIDC industrial estates or private industrial zones require formal building plan sanction. Front setbacks of at least 6 meters and side/rear setbacks of 4.5 meters are mandatory for plots up to 5 acres to ensure internal access for fire and rescue apparatus.",
        "text": "All industrial structures within MIDC industrial estates or designated industrial zones require formal building plan sanction. Front setbacks of at least 6 meters on roads up to 15m width and 9 to 12 meters on wider arterial roads are mandatory. Side and rear setbacks of at least 4.5 meters are mandatory for plots up to 5 acres to ensure clear peripheral driveway for fire tenders and emergency rescue apparatus.",
        "lang": "en",
        "tags": ["midc", "civil", "setback", "building", "land", "zoning"],
        "tags": ["midc", "civil", "setback", "building", "land", "zoning", "बांधकाम", "अंतर", "रस्ता"],
    },
    {
        "id": "kb-midc-002",
        "doc_id": "midc-fsi-far-norms",
        "title": "MIDC Floor Space Index (FSI) & Permissible Ground Coverage",
        "issuer": "Maharashtra Industrial Development Corporation (MIDC)",
        "section": "Regulation 6: Industrial FSI and Premium FAR Guidelines",
        "text": "The standard basic Floor Space Index (FSI) for industrial plots in MIDC is 1.0. Additional premium FSI up to 1.5 is permissible in standard industrial zones, and up to 2.5 for IT/ITES and biotech parks upon payment of premium charges. Maximum ground coverage permitted is 50% for standard manufacturing plots, leaving remaining land for setbacks, parking, internal vehicular circulation, and mandatory 10% green tree belt.",
        "lang": "en",
        "tags": ["midc", "fsi", "far", "ground-coverage", "built-up-area", "एफएसआय", "क्षेत्रफळ"],
    },
    {
        "id": "kb-midc-003",
        "doc_id": "midc-land-allotment-policy-2022",
        "title": "MIDC Land Allotment Procedure & 95-Year Industrial Lease Policy",
        "issuer": "Maharashtra Industrial Development Corporation (MIDC)",
        "section": "Chapter 2: Online Plot Application and Possession Protocol",
        "text": "Industrial plots in MIDC are allotted through the online portal on a 95-year renewable lease. After submission of project report, water/power requirement estimate, and earnest money deposit (EMD), the Allotment Committee evaluates applications based on project viability and employment potential. An Offer Letter is issued, requiring 100% lease premium payment within 30 to 90 days, followed by execution of Agreement to Lease and formal site possession within 21 days.",
        "lang": "en",
        "tags": ["midc", "land-allotment", "lease", "plot", "possession", "भूखंड", "जागा", "वाटप", "करार"],
    },
    {
        "id": "kb-midc-004",
        "doc_id": "midc-subletting-transfer-2023",
        "title": "MIDC Plot Transfer, Subletting, and Mortgage NOC Rules",
        "issuer": "Maharashtra Industrial Development Corporation (MIDC)",
        "section": "Policy Circular 18: Differential Transfer Premium & Sub-lease Charges",
        "text": "Transfer of MIDC industrial plots to a third party requires prior permission from the Chief Executive Officer (CEO) of MIDC and payment of Differential Transfer Premium (ranging from 2.5% to 5% of prevailing MIDC commercial land rates). Subletting part of the built premises is allowed for compatible industrial or warehousing use upon paying annual subletting fees. Obtaining a No Objection Certificate (NOC) for mortgaging the leasehold rights to nationalized or scheduled banks is processed within 7 working days.",
        "lang": "en",
        "tags": ["midc", "transfer", "subletting", "mortgage", "noc", "हस्तांतरण", "भाडेपट्टा", "कर्ज"],
    },
    {
        "id": "kb-midc-005",
        "doc_id": "midc-water-power-connection",
        "title": "MIDC Water Connection and Power Feeder Infrastructure Policy",
        "issuer": "Maharashtra Industrial Development Corporation (MIDC)",
        "section": "Infrastructure Regulations: Utility Supply Sanctions",
        "text": "MIDC provides industrial water supply based on a standard benchmark allocation of 10 to 45 cubic meters per day per acre depending on industry category. Units requiring heavy water consumption (above 100 KLD) must submit a water conservation and effluent recycling plan. Electricity supply is routed through MSEDCL substations within the industrial park with options for dual-circuit 11kV or 33kV dedicated express feeders for continuous processing plants.",
        "lang": "en",
        "tags": ["midc", "water-connection", "power", "msedcl", "electricity", "पाणी-पुरवठा", "वीज"],
    },

    # ── 3. DISH (Directorate of Industrial Safety & Health) ──────────────────────
    {
        "id": "kb-dish-001",
        "doc_id": "factories-act-1948",
        "title": "Factories Act 1948 & Maharashtra Factories Rules 1963",
        "issuer": "Directorate of Industrial Safety & Health (DISH)",
        "section": "Section 6: Approval of Plans and Licensing of Factories",
        "text": "Before starting construction or expanding manufacturing operations employing 10 or more workers with power, detailed factory layout blueprints specifying machinery spacing, emergency escape routes, and ventilation must be submitted to DISH for formal safety sanction.",
        "text": "Before starting construction or expanding manufacturing operations employing 10 or more workers with power, or 20 or more workers without power, detailed factory layout blueprints specifying machinery spacing, emergency escape routes, and ventilation must be submitted to DISH on Form 1 for formal safety sanction. Factory License on Form 2 must be obtained before commencing production and renewed annually or for a block of up to 10 years.",
        "lang": "en",
        "tags": ["dish", "factory", "machinery", "safety", "occupational"],
        "tags": ["dish", "factory", "machinery", "safety", "occupational", "कारखाना", "कामगार", "सुरक्षा", "परवाना"],
    },
    {
        "id": "kb-dish-002",
        "doc_id": "dish-machinery-spacing-cubic-space",
        "title": "DISH Machine Spacing, Cubic Air Space, and Pathway Standards",
        "issuer": "Directorate of Industrial Safety & Health (DISH)",
        "section": "Section 16 & 21: Workroom Air Space and Machine Safeguards",
        "text": "Under Section 16 of the Factories Act 1948, every workroom must provide at least 14.2 cubic meters (500 cubic feet) of air space per worker, excluding space occupied by machinery. Clear passageways between machinery rows must not be less than 1.2 meters in width, and main transport aisles must be at least 1.5 meters wide. All moving dangerous parts of machinery (flywheels, pulleys, driving belts) must be securely fenced by safeguards of substantial construction.",
        "lang": "en",
        "tags": ["dish", "air-space", "machinery-spacing", "aisle", "fencing", "जागा", "यंत्रे", "सुरक्षितता"],
    },
    {
        "id": "kb-dish-003",
        "doc_id": "dish-hazardous-process-welfare",
        "title": "DISH Hazardous Process Safeguards & Mandatory Worker Welfare",
        "issuer": "Directorate of Industrial Safety & Health (DISH)",
        "section": "Sections 41B, 45, 46, 48: Safety Committees, Canteens, and Crèches",
        "text": "Factories carrying out hazardous processes (under Section 2cb) must constitute a joint Bi-partite Safety Committee with equal representation of workers and management, formulate an On-site Disaster Management Plan, and maintain pre-employment and annual medical examination records on Form 7. Statutory welfare amenities are mandatory: First Aid boxes (1 per 150 workers), Ambulance Room (for 500+ workers), Canteen (for 250+ workers), Rest Shelters (for 150+ workers), Crèche (where more than 30 women workers are employed), and qualified Safety Officer (for 1000+ workers, or 100+ workers in hazardous factories).",
        "lang": "en",
        "tags": ["dish", "hazardous-process", "safety-officer", "canteen", "creche", "welfare", "कॅन्टीन", "पाळणाघर", "आरोग्य"],
    },

    # ── 4. Fire Services (Directorate of Maharashtra Fire Services) ──────────────
    {
        "id": "kb-fire-001",
        "doc_id": "fire-act-2006",
        "title": "Maharashtra Fire Prevention and Life Safety Measures Act 2006",
        "issuer": "Directorate of Maharashtra Fire Services",
        "section": "Section 3 & Schedule II: Life Safety Clearance Certificate",
        "text": "Industrial units with built-up area exceeding 500 sqm or occupying plots larger than 1 acre must install dedicated fire hydrant rings, automatic sprinkler systems, and on-site static water storage tanks (minimum 100,000 liters for hazardous units) prior to receiving Provisional Fire NOC.",
        "text": "Industrial units with built-up area exceeding 500 sqm or occupying plots larger than 1 acre must install dedicated fire hydrant rings, automatic sprinkler systems, and on-site static water storage tanks (minimum 100,000 liters for hazardous units) prior to receiving Provisional Fire NOC. Final Fire NOC is issued only after site inspection verifies functional pumps, smoke detectors, and clear fire escape routes.",
        "lang": "en",
        "tags": ["fire", "life-safety", "hydrant", "water-tank", "noc"],
        "tags": ["fire", "life-safety", "hydrant", "water-tank", "noc", "अग्निशमन", "ना-हरकत", "पाण्याची-टाकी"],
    },
    {
        "id": "kb-fire-002",
        "doc_id": "fire-water-tank-pump-specs",
        "title": "Statutory Fire Water Reservoir Sizing and Pump Specifications",
        "issuer": "Directorate of Maharashtra Fire Services",
        "section": "Rule 12: Underground and Overhead Fire Water Storage Standards",
        "text": "For industrial buildings: Light hazard premises require minimum 50,000 liters dedicated underground static fire water storage; Moderate hazard (engineering, plastics, warehouses) requires minimum 100,000 to 150,000 liters; High hazard chemical or explosive complexes require minimum 200,000 to 300,000 liters plus 20,000 liters overhead tank. Dedicated fire pump setup must include one main electric pump (minimum 2280 LPM / 600 GPM at 7 kg/cm2 pressure), one diesel standby engine pump of identical capacity, and one jockey pump (180 LPM) with automatic pressure sensing switch.",
        "lang": "en",
        "tags": ["fire", "reservoir", "water-tank", "pump", "capacity", "lpm", "प्रेशर", "पंप", "टाकी"],
    },
    {
        "id": "kb-fire-003",
        "doc_id": "fire-audit-form-b",
        "title": "Bi-Annual Fire Safety Audit & Form B Renewal Compliance",
        "issuer": "Directorate of Maharashtra Fire Services",
        "section": "Section 3(3): Six-Monthly Compliance Certificate (Form B)",
        "text": "Under Section 3(3) of the Maharashtra Fire Act 2006, the owner or occupier of every industrial building must submit a certificate in 'Form B' issued by a Government Licensed Fire Agency twice every year—once in January and once in July—certifying that all fire fighting installations (hydrants, sprinklers, extinguishers, alarms, and pumps) are in pristine, working condition. Failure to submit Form B renders the premises liable for cancellation of operating license.",
        "lang": "en",
        "tags": ["fire", "audit", "form-b", "compliance", "inspection", "तपासणी", "प्रमाणपत्र", "नूतनीकरण"],
    },

    # ── 5. State Incentives & Subsidies (Directorate of Industries & MSINS) ──────
    {
        "id": "kb-msins-001",
        "doc_id": "psi-2019",
        "doc_id": "psi-2019-2024",
        "title": "Package Scheme of Incentives (PSI 2019 / 2024)",
        "issuer": "Directorate of Industries, Maharashtra",
        "section": "Chapter 4: Capital Subsidy & Fiscal Incentives",
        "text": "Eligible Micro, Small, and Medium manufacturing units in Maharashtra can avail up to 40% to 80% capital subsidy on eligible fixed capital investment in plant and machinery, together with 100% exemption from Stamp Duty and Registration Fees on industrial land transfer.",
        "section": "Chapter 4: Capital Subsidy & Industrial Promotion Subsidy (IPS)",
        "text": "Eligible Micro, Small, and Medium manufacturing units in Maharashtra can avail up to 40% to 100% Industrial Promotion Subsidy (IPS) on eligible Gross Fixed Capital Investment (GFCI) in plant and machinery, disbursed through reimbursement of State Goods and Services Tax (SGST) over 7 to 10 years. Subsidy quantum varies by Taluka category: Zone A (Mumbai/Pune - minimum incentives), Zone B (intermediate), Zone C, Zone D, and Zone D+ (underdeveloped talukas, Vidarbha, Marathwada, and Naxal-affected areas receive maximum 80% to 100% GFCI subsidy ceiling).",
        "lang": "en",
        "tags": ["msins", "psi", "subsidy", "incentive", "stamp-duty", "msme"],
        "tags": ["msins", "psi", "subsidy", "incentive", "sgst", "ips", "msme", "अनुदान", "सवलत", "उद्योग-धोरण"],
    },
    {
        "id": "kb-msins-002",
        "doc_id": "startup-policy-2024",
        "title": "Maharashtra State Innovative Startup Policy 2024",
        "issuer": "Maharashtra State Innovation Society (MSINS)",
        "section": "Section 3: Innovation Vouchers and Seed Funding",
        "text": "Innovative enterprises developing hardware, deep-tech, or clean energy prototypes are eligible for seed vouchers of up to ₹15 Lakhs for testing, standardisation, and laboratory compliance support from government-recognized incubators.",
        "text": "Innovative enterprises developing hardware, deep-tech, clean energy, or biotechnology prototypes are eligible for innovation seed vouchers of up to ₹15 Lakhs for testing, prototyping, standardisation, and laboratory compliance support from government-recognized incubators. Additionally, startups receive 100% patent fee reimbursement up to ₹2 Lakhs for Indian patents and ₹10 Lakhs for international patents.",
        "lang": "en",
        "tags": ["incentives", "grant", "startup", "voucher", "msins", "seed"],
        "tags": ["incentives", "grant", "startup", "voucher", "msins", "seed", "पेटंट", "स्टार्टअप", "बीजभांडवल"],
    },
    {
        "id": "kb-msins-003",
        "doc_id": "psi-stamp-duty-power-subsidy",
        "title": "PSI 2019/2024 Stamp Duty Exemption & Electricity Duty Waiver",
        "issuer": "Directorate of Industries, Maharashtra",
        "section": "Fiscal Incentives: Power Tariff Subsidy and Stamp Duty Exemption",
        "text": "Eligible new MSME and large units in Category C, D, and D+ areas are entitled to: (1) 100% exemption from Stamp Duty and Registration Fees on acquisition of industrial land, lease agreements, and bank loan hypothecation mortgages; (2) 100% exemption from payment of Electricity Duty for 7 to 10 years; and (3) Power tariff subsidy of ₹1 to ₹2 per unit of electricity consumed for manufacturing units in Vidarbha, Marathwada, North Maharashtra, and tribal/D+ talukas for a period of 5 years.",
        "lang": "en",
        "tags": ["psi", "stamp-duty", "electricity-duty", "power-subsidy", "waiver", "मुद्रांक-शुल्क", "वीज-सवलत", "माफी"],
    },
    {
        "id": "kb-msins-004",
        "doc_id": "psi-interest-subsidy-msme",
        "title": "PSI Interest Subsidy Scheme for Micro, Small & Medium Enterprises",
        "issuer": "Directorate of Industries, Maharashtra",
        "section": "Regulation 8: Interest Subvention on Term Loans",
        "text": "Eligible Micro and Small enterprises in C, D, and D+ taluka categories obtaining term loans from recognized financial institutions or commercial banks for fixed capital investment in plant and machinery are eligible for an Interest Subsidy of 5% per annum on effective interest paid, capped at ₹5 Lakhs per annum for up to 5 years, provided the enterprise maintains timely loan repayment without default.",
        "lang": "en",
        "tags": ["psi", "interest-subsidy", "term-loan", "msme", "finance", "व्याज-अनुदान", "कर्ज", "बँक"],
    },
    {
        "id": "kb-msins-005",
        "doc_id": "cmegp-scheme-maharashtra",
        "title": "Chief Minister Employment Generation Programme (CMEGP)",
        "issuer": "Directorate of Industries, Maharashtra",
        "section": "Scheme Guidelines: Margin Money Capital Subsidy for New Ventures",
        "text": "The Chief Minister Employment Generation Programme (CMEGP) supports youth and first-generation entrepreneurs setting up manufacturing projects up to ₹50 Lakhs and service projects up to ₹20 Lakhs. The scheme provides government margin money capital subsidy of 15% to 25% for general category and up to 35% for SC/ST/women/minority/differently-abled entrepreneurs, requiring only 5% to 10% promoter own contribution with remaining project cost funded through bank term loans.",
        "lang": "en",
        "tags": ["cmegp", "employment", "entrepreneur", "margin-money", "subsidy", "सीएमईजीपी", "रोजगार", "उद्योजक"],
    },

    # ── 6. Single Window Timelines, Deemed Approvals & Redressal ────────────────
    {
        "id": "kb-sla-001",
        "doc_id": "mrpsa-2015",
        "title": "Maharashtra Right to Public Services Act 2015",
        "title": "Maharashtra Right to Public Services Act 2015 & SLA Timelines",
        "issuer": "Government of Maharashtra",
        "section": "Statutory Service Level Guarantees (SLA)",
        "text": "All statutory clearance applications submitted through the Udyog Samyog single window portal are governed by legally binding timelines: 30 days for MPCB Environmental Consent, 21 days for simultaneous scrutiny by MIDC, DISH, and Fire, and 7 days for final consolidated Single-Window permit issuance.",
        "section": "Statutory Service Level Guarantees (SLA) & Clearances Pipeline",
        "text": "All statutory clearance applications submitted through the Udyog Samyog single window portal are governed by legally binding timelines under the Maharashtra Right to Public Services Act 2015: 30 days for MPCB Environmental Consent to Establish, 21 days for simultaneous parallel scrutiny by MIDC (Civil), DISH (Factory Safety), and Fire Services, and 7 days for final consolidated Single-Window permit issuance. Total combined statutory turnaround is guaranteed within 45 to 60 days.",
        "lang": "en",
        "tags": ["sla", "timeline", "right-to-services", "delay", "statutory"],
        "tags": ["sla", "timeline", "right-to-services", "delay", "statutory", "कालावधी", "मुदत", "हमी", "सेवा-हक्क"],
    },
    {
        "id": "kb-sla-002",
        "doc_id": "deemed-approval-section-10",
        "title": "Statutory Deemed Approval Mechanism under Section 10",
        "issuer": "Government of Maharashtra",
        "section": "Section 10: Auto-Generation of Deemed Sanction Certificate",
        "text": "Under Section 10 of the Maharashtra Right to Public Services Act 2015, if any competent authority (MPCB, MIDC, DISH, or Fire Services) fails to either grant clearance or issue a formal deficiency query within the stipulated statutory SLA period, the clearance is deemed to have been granted by operation of law. The Udyog Samyog portal automatically generates an electronically signed Deemed Sanction Certificate with unique QR code verification, having the same legal validity as a regular clearance.",
        "lang": "en",
        "tags": ["deemed-approval", "mrpsa", "auto-approval", "sanction", "qr-code", "डीम्ड-मंजुरी", "आपोआप-मंजुरी", "कायदेशीर"],
    },
    {
        "id": "kb-sla-003",
        "doc_id": "query-response-scrutiny-rules",
        "title": "Departmental Deficiency Query Resolution & SLA Freeze Rules",
        "issuer": "Government of Maharashtra Single Window Directorate",
        "section": "Rule 7: Handling Officer Queries and Revision Dossier",
        "text": "When a scrutiny officer issues a deficiency query regarding missing drawings or ambiguous technical parameters, the applicant is granted 7 statutory working days to upload revised blueprints or submit written clarifications via their dashboard. During the pendency of the applicant's response, the statutory SLA clock is frozen. Once the applicant submits complete clarifications, the clock resumes and the officer must dispose of the application within 7 days.",
        "lang": "en",
        "tags": ["query", "deficiency", "dossier", "revision", "clock-freeze", "त्रुटी", "स्पष्टीकरण", "कागदपत्रे-पूर्तता"],
    },
    {
        "id": "kb-sla-004",
        "doc_id": "appellate-grievance-redressal",
        "title": "Statutory Appeals and Grievance Redressal Hierarchy",
        "issuer": "Government of Maharashtra",
        "section": "Section 18 & 19: First and Second Appellate Authorities",
        "text": "Applicants aggrieved by an unjust rejection, undue delay, or arbitrary fee demand can file a statutory online appeal on the portal within 30 days. The First Appellate Authority is the Regional Joint Director of Industries (disposing within 30 days). If unsatisfied, a Second Appeal can be filed before the Apex Committee chaired by the Development Commissioner (Industries) / Principal Secretary within 30 days, whose decision is binding on the department.",
        "lang": "en",
        "tags": ["appeal", "grievance", "redressal", "rejection", "hearing", "तक्रार", "अपील", "निवारण", "अन्याय"],
    },

    # ── 7. Document Checklists & Required Vault Artifacts ───────────────────────
    {
        "id": "kb-docs-001",
        "doc_id": "master-document-checklist",
        "title": "Master Statutory Document Checklist for Single Window Applications",
        "issuer": "Government of Maharashtra Single Window Directorate",
        "section": "Schedule C: Mandatory Documents for Phase 1 and Phase 2 Scrutiny",
        "text": "Standard clearance dossiers require: (1) Identity & Business: PAN Card, Certificate of Incorporation/Partnership Deed, Udyam MSME Registration; (2) Land & Civil: 7/12 Extract, Registered Sale Deed or MIDC Allotment Letter & Agreement to Lease, Contour and Site Layout Plan; (3) Environmental (MPCB): Process Flow Diagram, Water Balance Chart, Effluent Treatment Plant (ETP/STP) Blueprint, Ambient Air & Noise monitoring data; (4) Factory Safety (DISH): Plant Machinery Layout showing 1.2m machine clearances, ventilation section drawing; (5) Fire Safety: Hydrant network drawing, underground static tank layout, electrical load diagram; (6) Financial: CA Asset Valuation Certificate for Fixed Capital Investment verification.",
        "lang": "en",
        "tags": ["documents", "checklist", "blueprint", "vault", "pan", "udyam", "कागदपत्रे", "सूची", "नकाशा", "प्रमाणपत्र"],
    },
]

KB_DOCUMENTS = KB_CHUNKS

